<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13217" started-at="2018-08-16T07:54:48Z" finished-at="2018-08-16T07:55:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13217" started-at="2018-08-16T07:54:48Z" finished-at="2018-08-16T07:55:01Z">
      <class name="api.Tests.LoginFAILtest">
        <test-method status="PASS" signature="setup()[pri:0, instance:api.Tests.LoginFAILtest@6767c1fc]" name="setup" is-config="true" duration-ms="2032" started-at="2018-08-16T10:54:48Z" finished-at="2018-08-16T10:54:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:api.Tests.LoginFAILtest@6767c1fc]" name="initialize" is-config="true" duration-ms="476" started-at="2018-08-16T10:54:50Z" finished-at="2018-08-16T10:54:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="validateLoginFunctionality()[pri:0, instance:api.Tests.LoginFAILtest@6767c1fc]" name="validateLoginFunctionality" duration-ms="10254" started-at="2018-08-16T10:54:51Z" finished-at="2018-08-16T10:55:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at api.Tests.LoginFAILtest.validateLoginFunctionality(LoginFAILtest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFunctionality -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:api.Tests.LoginFAILtest@6767c1fc]" name="clearingSetup" is-config="true" duration-ms="136" started-at="2018-08-16T10:55:01Z" finished-at="2018-08-16T10:55:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:api.Tests.LoginFAILtest@6767c1fc]" name="tearDown" is-config="true" duration-ms="301" started-at="2018-08-16T10:55:01Z" finished-at="2018-08-16T10:55:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.Tests.LoginFAILtest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
